import "./globals.css";

export const metadata: { title: string, description: string } = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <div className="container"> {/* or "container-fluid" for full width */}
          {children}
        </div>
      </body>
    </html>
  );
}
